"""add relationships

Revision ID: e8e92c001391
Revises: eaf8077d41b2
Create Date: 2024-07-22 00:10:37.383514

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e8e92c001391'
down_revision: Union[str, None] = 'eaf8077d41b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
