"""added relatioships

Revision ID: f24ad9acf73d
Revises: eaf8077d41b2
Create Date: 2024-07-21 22:03:47.660990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24ad9acf73d'
down_revision: Union[str, None] = 'eaf8077d41b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
